<img src="../Pierian-Data-Logo.PNG">
<br>
<strong><center>Copyright 2019. Created by Jose Marcial Portilla.</center></strong>

# PyTorch Basics Exercises
For these exercises we'll create a tensor and perform several operations on it.

<div class="alert alert-danger" style="margin: 10px"><strong>IMPORTANT NOTE!</strong> Make sure you don't run the cells directly above the example output shown, <br>otherwise you will end up writing over the example output!</div>

### 1. Perform standard imports
Import torch and NumPy

In [ ]:
# CODE HERE
import torch
import numpy as np


### 2. Set the random seed for NumPy and PyTorch both to "42"
This allows us to share the same "random" results.

In [ ]:
# CODE HERE
torch.manual_seed(42)
np.random.seed(42)


### 3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive)

In [ ]:
# CODE HERE
arr = np.random.randint(0,5,6)
arr

array([1, 3, 1, 3, 4, 0])

In [ ]:
# DON'T WRITE HERE

[3 4 2 4 4 1]


### 4. Create a tensor "x" from the array above

In [ ]:
# CODE HERE
x = torch.from_numpy(arr)
x1 = torch.tensor(arr)

In [ ]:
x,x1

(tensor([1, 3, 1, 3, 4, 0]), tensor([1, 3, 1, 3, 4, 0]))

In [ ]:
# DON'T WRITE HERE

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)


### 5. Change the dtype of x from 'int32' to 'int64'
Note: 'int64' is also called 'LongTensor'

In [ ]:
# CODE HERE
x = x.type(torch.long)
print(x.dtype)
print(x.type())

torch.int64
torch.LongTensor


In [ ]:
# DON'T WRITE HERE

torch.LongTensor


### 6. Reshape x into a 3x2 tensor
There are several ways to do this.

In [ ]:
# CODE HERE
x = x.reshape(3,2)
x


tensor([[1, 3],
        [1, 3],
        [4, 0]])

In [ ]:
# DON'T WRITE HERE

tensor([[3, 4],
        [2, 4],
        [4, 1]])


### 7. Return the right-hand column of tensor x

In [ ]:
# CODE HERE
x[:,1:]


tensor([[3],
        [3],
        [0]])

In [ ]:
# DON'T WRITE HERE

tensor([[4],
        [4],
        [1]])


### 8. Without changing x, return a tensor of square values of x
There are several ways to do this.

In [ ]:
# CODE HERE
x.square()


tensor([[ 1,  9],
        [ 1,  9],
        [16,  0]])

In [ ]:
# DON'T WRITE HERE

### 9. Create a tensor "y" with the same number of elements as x, that can be matrix-multiplied with x
Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive).<br>
Think about what shape it should have to permit matrix multiplication.

In [ ]:
# CODE HERE
#y = torch.rand_int(0,5, size = (2,3))
y = torch.randint_like(x,low = 0 , high = 5)
y

tensor([[2, 4, 2],
        [3, 3, 4]])

In [ ]:
# DON'T WRITE HERE

### 10. Find the matrix product of x and y

In [ ]:
# CODE HERE
x@y

tensor([[11, 13, 14],
        [11, 13, 14],
        [ 8, 16,  8]])

In [ ]:
torch.mm(x,y)

tensor([[11, 13, 14],
        [11, 13, 14],
        [ 8, 16,  8]])

In [ ]:
torch.matmul(x,y)

tensor([[11, 13, 14],
        [11, 13, 14],
        [ 8, 16,  8]])

In [ ]:
x.mm(y)

tensor([[11, 13, 14],
        [11, 13, 14],
        [ 8, 16,  8]])

In [ ]:
# DON'T WRITE HERE

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])


## Great job!