<img src="../Pierian-Data-Logo.PNG">
<br>
<strong><center>Copyright 2019. Created by Jose Marcial Portilla.</center></strong>

# Tensor Operations
This section covers:
* Indexing and slicing
* Reshaping tensors (tensor views)
* Tensor arithmetic and basic operations
* Dot products
* Matrix multiplication
* Additional, more advanced operations

## Perform standard imports

In [1]:
import torch
import numpy as np

## Indexing and slicing
Extracting specific values from a tensor works just the same as with NumPy arrays<br>
<img src='../Images/arrayslicing.png' width="500" style="display: inline-block"><br><br>
Image source: http://www.scipy-lectures.org/_images/numpy_indexing.png

In [9]:
x = torch.arange(6).reshape(shape = (3,2))
print(x)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [10]:
# Grabbing the right hand column values
x[:,1]

tensor([1, 3, 5])

In [11]:
# Grabbing the right hand column as a (3,1) slice
x[:,1:]

tensor([[1],
        [3],
        [5]])

## Reshape tensors with <tt>.view()</tt>
<a href='https://pytorch.org/docs/master/tensors.html#torch.Tensor.view'><strong><tt>view()</tt></strong></a> and <a href='https://pytorch.org/docs/master/torch.html#torch.reshape'><strong><tt>reshape()</tt></strong></a> do essentially the same thing by returning a reshaped tensor without changing the original tensor in place.<br>
There's a good discussion of the differences <a href='https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch'>here</a>.

In [12]:
x = torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [15]:
x.view(10 , 1)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [16]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
x.view(5,2)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [18]:
# x is unchanged
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Views reflect the most current data

In [19]:
z = x.view(1,10)
print(z)
x[0]=234
print(z)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
tensor([[234,   1,   2,   3,   4,   5,   6,   7,   8,   9]])


### Views can infer the correct size
By passing in <tt>-1</tt> PyTorch will infer the correct value from the given tensor

In [20]:
x.view(2 , -1) # reshape to (2, ?)
# PyTorch computes the missing dimension: inferred size = total element/2 = 10/2 = 5
# so the final size is (2,5)

tensor([[234,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [21]:
x.view(5,-1)

tensor([[234,   1],
        [  2,   3],
        [  4,   5],
        [  6,   7],
        [  8,   9]])

In [22]:
x.view(-1,5)

tensor([[234,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

### Adopt another tensor's shape with <tt>.view_as()</tt>
<a href='https://pytorch.org/docs/master/tensors.html#torch.Tensor.view_as'><strong><tt>view_as(input)</tt></strong></a> only works with tensors that have the same number of elements.

In [25]:
x

tensor([234,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [26]:
z

tensor([[234,   1,   2,   3,   4,   5,   6,   7,   8,   9]])

In [24]:
x.view_as(z)

tensor([[234,   1,   2,   3,   4,   5,   6,   7,   8,   9]])

## Tensor Arithmetic
Adding tensors can be performed a few different ways depending on the desired result.<br>

As a simple expression:

In [31]:
a = torch.tensor([1,2,3] , dtype = torch.float)
b = torch.tensor([4,5,6] , dtype = torch.float)

print(a + b , a.type())

tensor([5., 7., 9.]) torch.FloatTensor


As arguments passed into a torch operation:

In [38]:
print(torch.add(a, b))

tensor([5., 7., 9.])


With an output tensor passed in as an argument:

In [41]:
result = torch.empty(3)
result

tensor([1.4552e-07, 0.0000e+00, 8.6213e-08])

In [42]:
result = torch.empty(3)
torch.add(a , b , out = result)
result

tensor([5., 7., 9.])

In [43]:
result = torch.empty(3)
torch.add(a , b , out=result)  # equivalent to result=torch.add(a,b)
print(result)

tensor([5., 7., 9.])


Changing a tensor in-place

In [ ]:
a.add_(b)  # equivalent to a=torch.add(a,b)
print(a)

tensor([5., 7., 9.])


In [44]:
a

tensor([1., 2., 3.])

In [45]:
b

tensor([4., 5., 6.])

In [46]:
a.fmod(b)

tensor([1., 2., 3.])

In [50]:
torch.sqrt(a)

tensor([1.0000, 1.4142, 1.7321])

In [51]:
a

tensor([1., 2., 3.])

In [52]:
1/a

tensor([1.0000, 0.5000, 0.3333])

In [53]:
torch.reciprocal(a)

tensor([1.0000, 0.5000, 0.3333])

In [54]:
torch.reciprocal(torch.zeros(10).view(2,-1))

tensor([[inf, inf, inf, inf, inf],
        [inf, inf, inf, inf, inf]])

In [55]:
torch.exp(a)

tensor([ 2.7183,  7.3891, 20.0855])

<div class="alert alert-info"><strong>NOTE:</strong> Any operation that changes a tensor in-place is post-fixed with an underscore _.
    <br>In the above example: <tt>a.add_(b)</tt> changed <tt>a</tt>.</div>

### Basic Tensor Operations
<table style="display: inline-block">
<caption style="text-align: center"><strong>Arithmetic</strong></caption>
<tr><th>OPERATION</th><th>FUNCTION</th><th>DESCRIPTION</th></tr>
<tr><td>a + b</td><td>a.add(b)</td><td>element wise addition</td></tr>
<tr><td>a - b</td><td>a.sub(b)</td><td>subtraction</td></tr>
<tr><td>a * b</td><td>a.mul(b)</td><td>multiplication</td></tr>
<tr><td>a / b</td><td>a.div(b)</td><td>division</td></tr>
<tr><td>a % b</td><td>a.fmod(b)</td><td>modulo (remainder after division)</td></tr>
<tr><td>a<sup>b</sup></td><td>a.pow(b)</td><td>power</td></tr>
<tr><td>&nbsp;</td><td></td><td></td></tr>
</table>

<table style="display: inline-block">
<caption style="text-align: center"><strong>Monomial Operations</strong></caption>
<tr><th>OPERATION</th><th>FUNCTION</th><th>DESCRIPTION</th></tr>
<tr><td>|a|</td><td>torch.abs(a)</td><td>absolute value</td></tr>
<tr><td>1/a</td><td>torch.reciprocal(a)</td><td>reciprocal</td></tr>
<tr><td>$\sqrt{a}$</td><td>torch.sqrt(a)</td><td>square root</td></tr>
<tr><td>log(a)</td><td>torch.log(a)</td><td>natural log</td></tr>
<tr><td>e<sup>a</sup></td><td>torch.exp(a)</td><td>exponential</td></tr>
<tr><td>12.34  ==>  12.</td><td>torch.trunc(a)</td><td>truncated integer</td></tr>
<tr><td>12.34  ==>  0.34</td><td>torch.frac(a)</td><td>fractional component</td></tr>
</table>

<table style="display: inline-block">
<caption style="text-align: center"><strong>Trigonometry</strong></caption>
<tr><th>OPERATION</th><th>FUNCTION</th><th>DESCRIPTION</th></tr>
<tr><td>sin(a)</td><td>torch.sin(a)</td><td>sine</td></tr>
<tr><td>cos(a)</td><td>torch.sin(a)</td><td>cosine</td></tr>
<tr><td>tan(a)</td><td>torch.sin(a)</td><td>tangent</td></tr>
<tr><td>arcsin(a)</td><td>torch.asin(a)</td><td>arc sine</td></tr>
<tr><td>arccos(a)</td><td>torch.acos(a)</td><td>arc cosine</td></tr>
<tr><td>arctan(a)</td><td>torch.atan(a)</td><td>arc tangent</td></tr>
<tr><td>sinh(a)</td><td>torch.sinh(a)</td><td>hyperbolic sine</td></tr>
<tr><td>cosh(a)</td><td>torch.cosh(a)</td><td>hyperbolic cosine</td></tr>
<tr><td>tanh(a)</td><td>torch.tanh(a)</td><td>hyperbolic tangent</td></tr>
</table>

<table style="display: inline-block">
<caption style="text-align: center"><strong>Summary Statistics</strong></caption>
<tr><th>OPERATION</th><th>FUNCTION</th><th>DESCRIPTION</th></tr>
<tr><td>$\sum a$</td><td>torch.sum(a)</td><td>sum</td></tr>
<tr><td>$\bar a$</td><td>torch.mean(a)</td><td>mean</td></tr>
<tr><td>a<sub>max</sub></td><td>torch.max(a)</td><td>maximum</td></tr>
<tr><td>a<sub>min</sub></td><td>torch.min(a)</td><td>minimum</td></tr>
<tr><td colspan="3">torch.max(a,b) returns a tensor of size a<br>containing the element wise max between a and b</td></tr>
</table>

<div class="alert alert-info"><strong>NOTE:</strong> Most arithmetic operations require float values. Those that do work with integers return integer tensors.<br>
For example, <tt>torch.div(a,b)</tt> performs floor division (truncates the decimal) for integer types, and classic division for floats.</div>

#### Use the space below to experiment with different operations

In [56]:
a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(torch.add(a,b).sum())

tensor(21.)


## Dot products
A <a href='https://en.wikipedia.org/wiki/Dot_product'>dot product</a> is the sum of the products of the corresponding entries of two 1D tensors. If the tensors are both vectors, the dot product is given as:<br>

$\begin{bmatrix} a & b & c \end{bmatrix} \;\cdot\; \begin{bmatrix} d & e & f \end{bmatrix} = ad + be + cf$

If the tensors include a column vector, then the dot product is the sum of the result of the multiplied matrices. For example:<br>
$\begin{bmatrix} a & b & c \end{bmatrix} \;\cdot\; \begin{bmatrix} d \\ e \\ f \end{bmatrix} = ad + be + cf$<br><br>
Dot products can be expressed as <a href='https://pytorch.org/docs/stable/torch.html#torch.dot'><strong><tt>torch.dot(a,b)</tt></strong></a> or `a.dot(b)` or `b.dot(a)`

In [57]:
a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a.mul(b)) # for reference
print()
print(a.dot(b))

tensor([ 4., 10., 18.])

tensor(32.)


<div class="alert alert-info"><strong>NOTE:</strong> There's a slight difference between <tt>torch.dot()</tt> and <tt>numpy.dot()</tt>. While <tt>torch.dot()</tt> only accepts 1D arguments and returns a dot product, <tt>numpy.dot()</tt> also accepts 2D arguments and performs matrix multiplication. We show matrix multiplication below.</div>

## Matrix multiplication
2D <a href='https://en.wikipedia.org/wiki/Matrix_multiplication'>Matrix multiplication</a> is possible when the number of columns in tensor <strong><tt>A</tt></strong> matches the number of rows in tensor <strong><tt>B</tt></strong>. In this case, the product of tensor <strong><tt>A</tt></strong> with size $(x,y)$ and tensor <strong><tt>B</tt></strong> with size $(y,z)$ results in a tensor of size $(x,z)$
<div>
<div align="left"><img src='../Images/Matrix_multiplication_diagram.png' align="left"><br><br>

$\begin{bmatrix} a & b & c \\
d & e & f \end{bmatrix} \;\times\; \begin{bmatrix} m & n \\ p & q \\ r & s \end{bmatrix} = \begin{bmatrix} (am+bp+cr) & (an+bq+cs) \\
(dm+ep+fr) & (dn+eq+fs) \end{bmatrix}$</div></div>

<div style="clear:both">Image source: <a href='https://commons.wikimedia.org/wiki/File:Matrix_multiplication_diagram_2.svg'>https://commons.wikimedia.org/wiki/File:Matrix_multiplication_diagram_2.svg</a></div>

Matrix multiplication can be computed using <a href='https://pytorch.org/docs/stable/torch.html#torch.mm'><strong><tt>torch.mm(a,b)</tt></strong></a> or `a.mm(b)` or `a @ b`

In [59]:
a = torch.tensor([[0,2,4] , [1,3,5]], dtype=torch.float)
b = torch.tensor([[6,7],[8,9],[10,11]], dtype=torch.float)

print('a : ' , a.size())
print('b : ' , b.size())
print('a x b : ' , torch.mm(a,b).size())

a :  torch.Size([2, 3])
b :  torch.Size([3, 2])
a x b :  torch.Size([2, 2])


In [60]:
print("a: ",a , "b: ",b , sep ='\n\n')

a: 

tensor([[0., 2., 4.],
        [1., 3., 5.]])

b: 

tensor([[ 6.,  7.],
        [ 8.,  9.],
        [10., 11.]])


In [61]:
print(torch.mm(a,b)) #mm: matrix multiplication

tensor([[56., 62.],
        [80., 89.]])


In [62]:
print(a.mm(b))

tensor([[56., 62.],
        [80., 89.]])


In [63]:
print(a @ b)

tensor([[56., 62.],
        [80., 89.]])


In [64]:
print(torch.matmul(a,b))

tensor([[56., 62.],
        [80., 89.]])


### Matrix multiplication with broadcasting
Matrix multiplication that involves <a href='https://pytorch.org/docs/stable/notes/broadcasting.html#broadcasting-semantics'>broadcasting</a> can be computed using <a href='https://pytorch.org/docs/stable/torch.html#torch.matmul'><strong><tt>torch.matmul(a,b)</tt></strong></a> or `a.matmul(b)` or `a @ b`

In [65]:
t1 = torch.randn(2, 3, 4)
print(f"t1 :{t1}")
t2 = torch.randn(4, 5)
print(f"t2 :{t2}")
print(torch.matmul(t1, t2).size())
print(f"t1 * t2: {torch.matmul(t1,t2)}")

t1 :tensor([[[-0.8866,  0.5904, -1.0151, -0.9067],
         [ 1.5877,  0.6147,  0.2427,  0.4345],
         [ 0.1370,  0.6614,  0.5617, -1.3502]],

        [[ 0.4814, -0.0039,  0.2382,  0.4548],
         [-1.5800,  0.7128,  0.7382,  0.2402],
         [ 0.5192, -0.3305,  1.1002, -0.3783]]])
t2 :tensor([[-0.8661, -0.1238, -0.7616, -1.2100,  2.2249],
        [ 0.8267, -0.0201, -0.6856,  0.7324, -1.5070],
        [ 1.5791,  0.4893,  0.2360,  1.4513,  0.3705],
        [ 0.6363,  0.1503,  0.3033,  0.1511,  1.5949]])
torch.Size([2, 3, 5])
t1 * t2: tensor([[[-0.9239, -0.5350, -0.2442, -0.1050, -4.6846],
         [-0.2072, -0.0249, -1.4415, -1.0531,  3.3892],
         [ 0.4561,  0.0417, -0.8348,  0.9299, -2.6373]],

        [[ 0.2453,  0.1253, -0.1698, -0.1710,  1.8905],
         [ 3.2761,  0.5786,  0.9616,  3.5415, -3.9327],
         [ 0.7737,  0.4238, -0.0239,  0.6692,  1.4575]]])


In [66]:
t1 @ t2

tensor([[[-0.9239, -0.5350, -0.2442, -0.1050, -4.6846],
         [-0.2072, -0.0249, -1.4415, -1.0531,  3.3892],
         [ 0.4561,  0.0417, -0.8348,  0.9299, -2.6373]],

        [[ 0.2453,  0.1253, -0.1698, -0.1710,  1.8905],
         [ 3.2761,  0.5786,  0.9616,  3.5415, -3.9327],
         [ 0.7737,  0.4238, -0.0239,  0.6692,  1.4575]]])

In [70]:
torch.matmul(t1,t2)

tensor([[[-0.9239, -0.5350, -0.2442, -0.1050, -4.6846],
         [-0.2072, -0.0249, -1.4415, -1.0531,  3.3892],
         [ 0.4561,  0.0417, -0.8348,  0.9299, -2.6373]],

        [[ 0.2453,  0.1253, -0.1698, -0.1710,  1.8905],
         [ 3.2761,  0.5786,  0.9616,  3.5415, -3.9327],
         [ 0.7737,  0.4238, -0.0239,  0.6692,  1.4575]]])

However, the same operation raises a <tt><strong>RuntimeError</strong></tt> with <tt>torch.mm()</tt>:

___
# Advanced operations

## L2 or Euclidian Norm
See <a href='https://pytorch.org/docs/stable/torch.html#torch.norm'><strong><tt>torch.norm()</tt></strong></a>

The <a href='https://en.wikipedia.org/wiki/Norm_(mathematics)#Euclidean_norm'>Euclidian Norm</a> gives the vector norm of $x$ where $x=(x_1,x_2,...,x_n)$.<br>
It is calculated as<br>

${\displaystyle \left\|{\boldsymbol {x}}\right\|_{2}:={\sqrt {x_{1}^{2}+\cdots +x_{n}^{2}}}}$


When applied to a matrix, <tt>torch.norm()</tt> returns the <a href='https://en.wikipedia.org/wiki/Matrix_norm#Frobenius_norm'>Frobenius norm</a> by default.

In [71]:
x = torch.tensor([2.,5.,8.,14.])
x.norm()

tensor(17.)

In [72]:
x.square().sum().sqrt()

tensor(17.)

## Number of elements
See <a href='https://pytorch.org/docs/stable/torch.html#torch.numel'><strong><tt>torch.numel()</tt></strong></a>

Returns the number of elements in a tensor.

In [73]:
x = torch.ones(3,7)
x.numel() # x.numel() = x.shape[0] * x.shape[1]

21

In [74]:
x.shape[0] * x.shape[1]

21

This can be useful in certain calculations like Mean Squared Error:<br>
<tt>
def mse(t1, t2):<br>
&nbsp;&nbsp;&nbsp;&nbsp;diff = t1 - t2<br>
    &nbsp;&nbsp;&nbsp;&nbsp;return torch.sum(diff * diff) / diff<strong>.numel()</strong></tt>

## Great work!