<img src="../Pierian-Data-Logo.PNG">
<br>
<strong><center>Copyright 2019. Created by Jose Marcial Portilla.</center></strong>

# PyTorch Basics Exercises
For these exercises we'll create a tensor and perform several operations on it.

<div class="alert alert-danger" style="margin: 10px"><strong>IMPORTANT NOTE!</strong> Make sure you don't run the cells directly above the example output shown, <br>otherwise you will end up writing over the example output!</div>

### 1. Perform standard imports
Import torch and NumPy

In [1]:
# CODE HERE
import torch
import numpy as np


### 2. Set the random seed for NumPy and PyTorch both to "42"
This allows us to share the same "random" results.

In [2]:
# CODE HERE
torch.manual_seed(42)
np.random.seed(42)


### 3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive)

In [3]:
# CODE HERE
arr = np.random.randint(low = 0, high = 5, size = 6)
arr

array([3, 4, 2, 4, 4, 1])

### 4. Create a tensor "x" from the array above

In [4]:
# CODE HERE
x = torch.from_numpy(arr)
x1 = torch.tensor(arr)

In [5]:
x,x1

(tensor([3, 4, 2, 4, 4, 1]), tensor([3, 4, 2, 4, 4, 1]))

### 5. Change the dtype of x from 'int32' to 'int64'
Note: 'int64' is also called 'LongTensor'

In [6]:
# CODE HERE
x = x.type(torch.long)
print(x.dtype , x.type() , sep = '\n')

torch.int64
torch.LongTensor


### 6. Reshape x into a 3x2 tensor
There are several ways to do this.

In [7]:
# CODE HERE
x = x.reshape(3,2)
print(x)

tensor([[3, 4],
        [2, 4],
        [4, 1]])


### 7. Return the right-hand column of tensor x

In [8]:
# CODE HERE
x[:,1:]


tensor([[4],
        [4],
        [1]])

In [9]:
# DON'T WRITE HERE

### 8. Without changing x, return a tensor of square values of x
There are several ways to do this.

In [10]:
# CODE HERE
x.square()


tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])

### 9. Create a tensor "y" with the same number of elements as x, that can be matrix-multiplied with x
Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive).<br>
Think about what shape it should have to permit matrix multiplication.

In [21]:
# CODE HERE
y = torch.randint(0,5, size = (2,3))
y

tensor([[0, 4, 1],
        [2, 0, 0]])

In [22]:
y.shape , x.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

### 10. Find the matrix product of x and y

In [23]:
# CODE HERE
torch.matmul(x,y)

tensor([[ 8, 12,  3],
        [ 8,  8,  2],
        [ 2, 16,  4]])

In [24]:
torch.mm(x,y)

tensor([[ 8, 12,  3],
        [ 8,  8,  2],
        [ 2, 16,  4]])

In [25]:
x.mm(y)

tensor([[ 8, 12,  3],
        [ 8,  8,  2],
        [ 2, 16,  4]])

## Great job!